function [turn_angles_arr, t2_arr, turn_angles_ov_arr, t2_ov_arr] = avoid_simplified_batch( ...
    x_h0, y_h0, vx_h0, vy_h0, ...
    x_i0, y_i0, vx_i0, vy_i0, ...
    x_h0_ov, y_h0_ov, vx_h0_ov, vy_h0_ov, ...
    x_i0_ov, y_i0_ov, vx_i0_ov, vy_i0_ov, ...
    sigma_al, sigma_cross, time_resol, nz, ...
    DMOD, vx_w, vy_w, max_bank, max_roll_rate)

    n = numel(x_h0);

    [ta0, ~, t20] = avoidSimplified( ...
        x_h0(1), y_h0(1), vx_h0(1), vy_h0(1), ...
        x_i0(1), y_i0(1), vx_i0(1), vy_i0(1), ...
        sigma_al, sigma_cross, time_resol, nz, ...
        DMOD, vx_w, vy_w, max_bank, max_roll_rate);

    m = numel(ta0);

    turn_angles_arr    = zeros(m, n);
    t2_arr             = zeros(m, n);
    turn_angles_ov_arr = zeros(m, n);
    t2_ov_arr          = zeros(m, n);

    for k = 1:n
        [ta, ~, t2] = avoidSimplified( ...
            x_h0(k), y_h0(k), vx_h0(k), vy_h0(k), ...
            x_i0(k), y_i0(k), vx_i0(k), vy_i0(k), ...
            sigma_al, sigma_cross, time_resol, nz, ...
            DMOD, vx_w, vy_w, max_bank, max_roll_rate);


        turn_angles_arr(:, k) = ta(:);
        t2_arr(:, k) = t2(:);

        [ta_ov, ~, t2_ov] = avoidSimplified( ...
            x_h0_ov(k), y_h0_ov(k), vx_h0_ov(k), vy_h0_ov(k), ...
            x_i0_ov(k), y_i0_ov(k), vx_i0_ov(k), vy_i0_ov(k), ...
            sigma_al, sigma_cross, time_resol, nz, ...
            DMOD, vx_w, vy_w, max_bank, max_roll_rate);

        turn_angles_ov_arr(:, k) = ta_ov(:);
        t2_ov_arr(:, k) = t2_ov(:);
    end
end
